
import 'package:flutter/material.dart';

class NotePadAiItem extends StatelessWidget {
  const NotePadAiItem({super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 15),
      margin: EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Color(0xffFFCC80),
        borderRadius: BorderRadius.circular(14),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          ListTile(
            contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 5),
            title: const Text(
              'NotePad AI ',
              style: TextStyle(
                fontSize: 26,
                fontWeight: FontWeight.bold,
                color: Colors.black,
              ),
            ),
            subtitle: Padding(
              padding: const EdgeInsets.symmetric(vertical: 10),
              child: Text(
                'This is a note item generated by AI,  ',
                style: TextStyle(
                  fontSize: 20,
                  color: Colors.black.withValues(alpha: .4),
                ),
              ),
            ),
            trailing: IconButton(
              icon: const Icon(
                Icons.delete_sharp,
                color: Colors.black,
                size: 38,
              ),
              onPressed: () {},
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(right: 18),
            child: Text(
              '18 / 6 / 2026',
              style: TextStyle(
                fontSize: 18,
                color: Colors.black.withValues(alpha: .4),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
